### ISSUE TITLE
How to use mason.js for a perfect grid of images

### ISSUE THREAD

**Issue by petpal** [DrewDahlman/Mason#17]
Hello there,
I was trying to get you by email but it didn't seem to work out so I'll try through here.
I would like to use mason.js for creating a perfect grid of images, my question is, how would i do it and if its even possible with mason.js?

These are the things I need it to do:

1) Create a perfect grid from inputted images of any size and any amount with no gaps at all.
2) In order to fill gaps in, the system can resize the images, however ratio should be kept (In case there will be still gaps, the system can also crop certain images).

What do you think?

Thanks for your help.

**Comment by petpal** [comment]
Hello
I managed to achieve this effect !!!! :)
look at this: it takes many random images of unkown size and amount and make a mason out of it:
http://petpal.co.il/generate

**Comment by sujan-tpc** [comment]
@petpal could you specify how you achieved your result?

**Comment by omidfi** [comment]
@petpal the page is not there anymore, would be nice if you could host your solution somewhere!

**Comment by mayankcpdixit** [comment]
I made something that may come handy: https://github.com/mayankcpdixit/grid-no-white

**Comment by DrewDahlman** [comment]
Please include a link and how this deals with mason.

**Comment by mayankcpdixit** [comment]
@DrewDahlman Hey,
I added a [link to github repo](https://github.com/mayankcpdixit/grid-no-white). It's not a wrapper around mason. It's just a lightweight image-grid module in JS.
Not much configurable. But it does the job.
