### ISSUE TITLE
filler blocks still repeating

### ISSUE THREAD

**Issue by pmasloch** [DrewDahlman/Mason#23]
Hi, I am working on a project where your script seems a perfect match! Unfortunately, the js still loads repeating boxes which is a big downside... There is a note that says the issue has been addresses in 6.1.13 fix. I wonder if I can get hold of the fix as it doesn't appear in the zipped files. 
Quite frankly, it is a  hard work well done but a little piece of the 'mosaic' is missing! Can you advice on how to make the js load each box one time only. Many thanks! Cheers. Pawel

**Comment by DrewDahlman** [comment]
check out this issue - https://github.com/DrewDahlman/Mason/issues/19
