### ISSUE TITLE
Uncaught TypeError: Cannot set property '4' of undefined 

### ISSUE THREAD

**Issue by versation-amanda** [DrewDahlman/Mason#31]
Hi there -

First of all, love the plugin!  Thank you.

Although everything still works on the frontend, I am receiving a JS error in my console: "Uncaught TypeError: Cannot set property '4' of undefined"

Seems to be the same as this issue: https://github.com/DrewDahlman/Mason/issues/10

If I use the minified version vs. non minified version I get the same error but instead of property '4', it's property '1'

This error is causing other issues with jQuery plugins, so I'm hoping to get it fixed.

I am using the most recent version of the script here: https://github.com/DrewDahlman/Mason/blob/master/mason.min.js

Thanks in advance!

**Comment by UnaOmnia** [comment]
I know someone huge into programming.. They get contracted by the feds from time to time.. I think they would be able to solve this.. anyone offering a reward for a graduate student to solve this? Just wondering..

**Comment by DrewDahlman** [comment]
Please see v2

**Comment by UnaOmnia** [comment]
Hey Drew,

If there is any way you can personally jump on to check out my project.. like over Skype.. I think that would help me complete it, and I think it would show you a lot about what your trying to do versus applications I have thought of.. What do you say? Meet up quid pro quo style?

**Comment by DrewDahlman** [comment]
Hey @UnaOmnia send me an email, I can do some consulting if needed I am not totally sure what you are trying to do, and it might not be a right fit for mason but shoot me an email and we can continue this conversation on a different channel.

**Comment by UnaOmnia** [comment]
Can you send me one first? Or let me know your email?

ted@unaomnia.com <-- I can delete after you message me. 

I plan to get a little further along, backup the site, and try to make our conversation light. Just want to go a little quicker on the back and forth, a short Q & A about how this could be integrated into WP loops (and then the WORLD!) ...

**Comment by UnaOmnia** [comment]
localnationalnews.com/url-test <-- lazy loaded all 375 posts in a category, in order, no duplicates - via AJAX $.post and array to string conversions of all post IDS - I.E. keeping track of boxes, filling boxes, and skipping IDs of posts that fill boxes, etc. 

Finally got it working nicer.. now to add more crap like styling etc. 

Why I want to talk to you? See any ways I can get load down, get methods more streamlined, also, to see if you can get ideas for your next version, or for a WordPress plugin etc.
