### ISSUE TITLE
Documentation issue: ratio

### ISSUE THREAD

**Issue by theseyi** [DrewDahlman/Mason#35]
The description for ratio is a bit vague, could this be explained a little more explicitly? 
"The ratio is a number that is used to create the blocks based on column count and width." has very little meaning as to what I should set this value to, in other words how do I calculate this value and what does it mean for my grid or block proportions?. Thanks.

**Comment by DrewDahlman** [comment]
Will add this to the updated readme.

**Comment by dabernathy89** [comment]
I know this is closed, but this is still very vague. There's no indication of what is done with the number or how we should decide on it.
