### ISSUE TITLE
Items repeating unnecessarily 

### ISSUE THREAD

**Issue by jonlambert** [DrewDahlman/Mason#54]
Hi!

This looks like an awesome plugin. I've just cracked it out on an example page, with 4 images as a test. 

``` javascript
$('.images').mason({
  itemSelector: '.image',
  ratio: 1.0,
  sizes: [
    [1, 1]
  ],
  layout: 'fluid'
});
```

I'd like them all to render with an equal size, and distribute evenly to fill the container. This the plugin does brilliantly. However, it doesn't just fill one line, it creates a 4x4 grid of images (obviously repeating each image 4 times) meaning the container is 4x the height it should be. I'm sure it's down to user error, but is there any way of disabling the repetition, and limiting the height of the container?

**Comment by atilkan** [comment]
same for me too.

**Comment by kayaj** [comment]
+1 here. 
I'm just looking into the code, maybe we can solve this ourselves. 
Maybe @DrewDahlman will deliver.

**Comment by DrewDahlman** [comment]
Can you post a fiddle?

**Comment by kayaj** [comment]
Hi Drew

I’m Am 7. Dezember 2015 bei 18:01:42, Drew Dahlman (notifications@github.com) schrieb:
Can you post a fiddle?

**Comment by kayaj** [comment]
doing this right now.

**Comment by kayaj** [comment]
I'm supplying 8 items in a grid with 4 columns. 
I'd expect MasonJS to arrange all the items in a 2x4 grid *without* fillers.

-> https://jsfiddle.net/ufvee0v3/

**Comment by DrewDahlman** [comment]
Ahh looks like there is a calculation issue - if you remove the borders it works as it should.. https://jsfiddle.net/ufvee0v3/4/ I will take a look at how sizing is being calculated to include better for borders.

**Comment by kayaj** [comment]
You're right @DrewDahlman - The code is pretty sensitive when it comes to widths. ;)
Still: Is there no option to skip fillers and use items instead? I want to prevent duplicate content.

**Comment by julien-gargot** [comment]
If you do not want fillers, I put a comment there about that : [#60]( https://github.com/DrewDahlman/Mason/issues/60#issuecomment-220297574)

**Comment by kokujin** [comment]
I was just going to create an issue on this. Is there now a documented way to make the images and their grids more predictable? I have the problem too that several tiles are repeating unnecessarily

**Comment by DrewDahlman** [comment]
@kokujin look at the promoted feature, you can assign classes and specify the dimensions of your elements based on a class and assigned sizing.
