### ISSUE TITLE
Adding and removing boxes

### ISSUE THREAD

**Issue by ktodyruik** [DrewDahlman/Mason#57]
Hi Drew 

This is just a question. Mason looks really good. 

The examples look like they are initialized once. 

How does mason deal with adding and removing items from the grid? 

Is it possible to animate (fade in/out) boxes on an existing grid? Modifying an existing grid with transitions.. 

Thanks 
Kerry

**Comment by DrewDahlman** [comment]
This deals with https://github.com/DrewDahlman/Mason/issues/67
