### ISSUE TITLE
Blocks not filling in space

### ISSUE THREAD

**Issue by dreamxcape** [DrewDahlman/Mason#59]
Hi,

I'm having trouble getting the masonry to work right. Sometimes, my rows aren't being completely filled by blocks, and an empty block is rendered. For example, I've set the sizes to be [1,1] and [2,1]. But sometimes, when a [2,1] block is rendered on a row, there should be space for a [1,1] block on the right; but in my case it's an empty space.

Here's an example of my issue: http://paperscrunch.com/mason-test/

Any idea why this is happening? Am I doing something wrong? Or is it an issue with bootstrap?

**Comment by DrewDahlman** [comment]
Just quickly looking at this it may be an issue with the transitions - seems that is causing mis-counts so it isn't filling the space properly.

**Comment by heaversm** [comment]
I'm having trouble with fillers too - it doesn't seem to be inserting any. Are we supposed to put the filler dom elements in manually or is it supposed to insert them dynamically. Either way, I can't seem to get them to render to cover gaps.

**Comment by DrewDahlman** [comment]
Working through issues tonight.

Mason will do 1 of 2 things:
- If no filler is specified it will copy at random elements from the grid to use as fillers.
- If you specify a filler this should be a dom element that is available for mason to use via a class name.
