### ISSUE TITLE
Fillers with different sizes

### ISSUE THREAD

**Issue by Nmaster88** [DrewDahlman/Mason#63]
I don't know if this is the right place to post, i'm new to github!

This script is amazing, but i have a suggestion that i think would be nice. Is there a way or plans to have the option to add fillers with different sizes to the grid? Thanks

**Comment by DrewDahlman** [comment]
hi @Nmaster88 since fillers are used as just that they only size to fill in the gaps - your primary content should get sized how you want using the promoted options with the sizing array.

**Comment by Nmaster88** [comment]
Ok so that means they will always 1 by 1 in the grid. I was just thinking it would be cool because the content is always reorganized to the left and fillers fill the gaps in the right.

**Comment by DrewDahlman** [comment]
Unfortunately this is how mason works. It needs things to fill the gaps and those gaps are calculated to be a 1x1 based on the ratio.
