### ISSUE TITLE
Example with multiple images?

### ISSUE THREAD

**Issue by kokujin** [DrewDahlman/Mason#69]
Can someone point me to an example usage with images? Thanks

**Comment by DrewDahlman** [comment]
http://codepen.io/DrewDahlman/pen/d3b564d8fb96b147cbf62a29c4c0e7e6/ here's a qick pen that shows how to work with images. set them as background images.

**Comment by kokujin** [comment]
That was quick, are you "the flash"?  Awesome. Thanks

**Comment by DrewDahlman** [comment]
http://31.media.tumblr.com/1f20ce6bc6c2b70670d3470ad1365367/tumblr_mp1a59KYYq1r4l7szo1_250.gif

**Comment by DrewDahlman** [comment]
So it all depends on how you set things up - in a scenario of 4 maybe set 2 as your primary blocks and then set the other two as your fillers. If you don't specify filler blocks it will reuse random blocks.

I would suggest also playing with your block sizes, 4 is a pretty low number so it's going attempt to fill the space using the base block size, so if you make them larger using promoted and set the grid size. you should be able to configure it to meet your needs.

Mess around with columns, ratio and sizes as well as promoted if you want to force a block to a specific size. You can fill an area exactly how you want but you need to play with settings to get that to work properly.

**Comment by kokujin** [comment]
Thanks. I'll try that out
